### ISSUE TITLE
Programmatically stop croner

### ISSUE THREAD

**Issue by davoam** [Hexagon/croner#26] opened 2021-12-22 16:42 UTC
Thanks for the library! 

Is there any way to programmatically stop croner? My Jest tests hangs until I manually kill tests process

**Comment by Hexagon** [comment] 2021-12-22 16:47
Yeah, you can stop it from both "inside" and "outside".

```javascript
const job = Cron('xxx', (_job) => { _job.stop();});

job.stop();```

Works? :)

**Comment by davoam** [comment] 2021-12-22 17:06
Thanks for the quick response! Yeah, I stopped all the jobs this way, but the process itself keeps running. If there are no running jobs, croner stops the process?

**Comment by Hexagon** [comment] 2021-12-22 17:44
Hmm, croner does not fork processes or anything, it's basically a ```setTimeout```, where ```.stop()``` run ```clearTimeout```. Are you sure your scheduled function does not leave anything running?

**Comment by davoam** [comment] 2021-12-22 19:17
> Hmm, croner does not fork processes or anything, it's basically a `setTimeout`, where `.stop()` run `clearTimeout`. Are you sure your scheduled function does not leave anything running?
> 
> If croner causes this, it would be awesome if you could pinpoint the problem and paste some code here, so i can have a look at it :)

I'll try when I have time :)

**Comment by Hexagon** [comment] 2021-12-22 21:15
Great, tried to reproduce it using different techniques, but this is the only one that continue running "unexpectedly".

````javascript
const Cron = require("croner");

async function runsToInfinity() { setTimeout(runsToInfinity, 1000); }

const job = Cron('* * * * * *', async (self) => {

    // No await
    runsToInfinity();

    // Option 1, will not stop execution
    console.log('Yay, done!');
    self.stop();
} );

// Option 2 (wait 2 seconds to make sure execution started)fter execution has started) 
// ... will not stop execution either
setTimeout( () => { 
    console.log('Yay, done again!'); 
    job.stop(); 
}, 2000);
```

**Comment by Hexagon** [comment] 2022-01-05 19:57
Closing this, since there is no steps to reproduce. 

Please reopen if you find/document a way to reproduce this

**Closed by Hexagon** 2022-01-05 19:57 UTC
Labels: question
