### ISSUE TITLE
Job won't run when scheduled with America/Anchorage time zone

### ISSUE THREAD

**Issue by victorird** [Hexagon/croner#238] opened 2024-02-03 01:19 UTC
**Describe the bug**
When creating job with time zone America/Anchorage, the job never runs. Getting `nextRun()` on the job returns an invalid date.

**To Reproduce**

Example: 
Schedule a job to run at certain time in America/Anchorage time zone. Log the job next run.
```
const job = Cron('0 0 * * *', { timezone: 'America/Anchorage' }, () => { console.log('Do something') })
console.log(`Next run: ${job.nextRun()}`)
```

**Expected behavior**
Job runs at midnight at America/Anchorage. Log will print correct next run date and time.

**Actual behavior**
Job never run. Log prints next run date as "invalid date"

**System:**
 - OS: Ubuntu 22.04
 - Runtime: Node.js 16.20.2
 - Croner Version: 7.0.4

**Additional context**
I believe this is due to Date.parse() not able to parse the Anchorage's obsolete zone name "AKST" and "AKDT".
```
console.log(Date.parse('2/3/2024, 1:17:26 AM AKST')
// Output: NaN
```
This thread suggests using UTC offset instead of using the obsolete zone name: https://stackoverflow.com/questions/31056823/javascript-date-parse-doesnt-accept-alaska-timezones

**Comment by Hexagon** [comment] 2024-02-03 08:20
Duplicate of https://github.com/Hexagon/croner/issues/225

**Closed** 2024-02-05 21:04 UTC
Labels: bug
