### ISSUE TITLE
Not working with Node 19.1 

### ISSUE THREAD

**Issue by kyrylkov** [Hexagon/croner#148] opened 2022-11-27 12:32 UTC
For us croner stops working with Node 19.1 on Windows and Linux

**Comment by Hexagon** [comment] 2022-11-27 12:36
Verified. Node 19 added to test matrix, and fails catastrophically.

Thanks for the report, will have a look asap.

**Comment by Hexagon** [comment] 2022-11-27 20:00
Node 19.1 is broken by a bug in upstream V8, the problem is fixed in 19.0, but still exist in 19.1. Nothing to do about this except to wait for a new release of node,

https://github.com/nodejs/node/issues/45171

**Comment by kyrylkov** [comment] 2022-11-27 20:11
@Hexagon Yep, that's what I suspected.  There was nothing in 19.1 vs 19.0 that could have broken it except a bug.  Upcoming 19.2 should address this taking into account that it was fixed in upstream V8.

Thanks!

**Comment by Hexagon** [comment] 2022-11-27 23:29
Working my way around the Node 19.1 bug

**Comment by Hexagon** [comment] 2022-11-27 23:42
Fixed in `5.3.5` 👍

**Closed by Hexagon** 2022-11-27 23:42 UTC

**Comment by kibertoad** [comment] 2023-01-04 15:53
@Hexagon This was fixed in 19.2.0, would it make sense to remove workaround now?

**Comment by Hexagon** [comment] 2023-01-04 16:33
@kibertoad Good point! The fix is just replacing narrow no break space with a normal space. Can keep it until we're sure that no one uses 19.1. If it isnt fixed in 19.1 too? Gotta check that
